# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!


pod 'ChromaColorPicker'
pod 'Google/SignIn'
pod 'GoogleAPIClientForREST'
pod 'GTMOAuth2', '~> 1.1.0'
pod 'GoogleAPIClientForREST/Calendar', '~> 1.2.1'
pod 'VerticalSlider'
pod 'SwiftOCR', :git => 'https://github.com/garnele007/SwiftOCR.git'

target 'SongProjector' do

end