# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!


pod 'GoogleSignIn'
pod 'GoogleAPIClientForREST'
pod 'GTMOAuth2', '~> 1.1.0'
pod 'GoogleAPIClientForREST/Calendar', '~> 1.2.1'
pod 'VerticalSlider'
pod 'SwiftKeychainWrapper'
pod 'FlexColorPicker'

pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'FirebaseFirestoreSwift'
pod 'Firebase/Storage'

target 'SongProjector' do

end