//
//  Organizations.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class Organizations: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _id: String?
    var _name: String?
    var _creationDate: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "churchbeam-mobilehub-249648808-Organizations"
    }
    
    class func hashKeyAttribute() -> String {

        return "_id"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_name"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_id" : "id",
               "_name" : "name",
               "_creationDate" : "creationDate",
        ]
    }
}
